//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_SeaLevelRise : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean goBack
        {
            get
            {
                return SteamVR_Actions.seaLevelRise_goBack;
            }
        }
        
        public virtual SteamVR_Action_Boolean sliderEdit
        {
            get
            {
                return SteamVR_Actions.seaLevelRise_sliderEdit;
            }
        }
        
        public virtual SteamVR_Action_Vector2 touchpadSLR
        {
            get
            {
                return SteamVR_Actions.seaLevelRise_touchpadSLR;
            }
        }
    }
}
